### ISSUE TITLE
Dockerfile broken

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [openairplay/goplay2#18]
Hey Alban

Thanks a lot for this project!!!

Seems like the provided Dockerfile currently does not build (no makefile).

Happy to send a PR for a working one though.

**Comment by AlbanSeurat** [comment]
I was about to remove docker support (see branch features/audio-sync).

I will merge your PR, thanks for the effort

**Comment by beagleboys** [comment]
sorry for reopening this but from my low docker knowledge it seems related. when I try to build I get this error:
`docker build --platform=linux/arm/v7 -t you/goplay2 .
Sending build context to Docker daemon  464.7MB
Step 1/22 : FROM    --platform=$BUILDPLATFORM golang:1.16   as fetcher
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument`

**Comment by dubo-dubon-duponey** [comment]
In transit right now.
Will look into this asap.

**Comment by dubo-dubon-duponey** [comment]
@beagleboys From a cursory look, my guess is that your version of docker is ancient (are you using an old distro package?).
Can we start by confirming that? (You can copy the output of 'docker info' here)

**Comment by chenyg0911** [comment]
I update docker veriosn to newest.
```
docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
Same problem as @beagleboys 

I direct set the platorm on docker file such as:
```
FROM    --platform=linux/amd64 golang:1.16   as fetcher
...
```
build still failed:
```
Step 12/22 : RUN     sed -Ei 's/main$/main non-free/g' /etc/apt/sources.list;         DEB_TARGET_ARCH="$(echo "$TARGETARCH$TARGETVARIANT" | sed -e "s/^armv6$/armel/" -e "s/^armv7$/armhf/" -e "s/^ppc64le$/ppc64el/" -e "s/^386$/i386/")";         dpkg --add-architecture "$DEB_TARGET_ARCH";         apt-get update;         apt-get install -qq --no-install-recommends             autoconf             libtool             crossbuild-essential-"$DEB_TARGET_ARCH"             libfdk-aac1:"$DEB_TARGET_ARCH"             libfdk-aac-dev:"$DEB_TARGET_ARCH"             portaudio19-dev:"$DEB_TARGET_ARCH"
 ---> Running in 91600bdb11d2
dpkg: error: architecture '' is reserved and cannot be added
Get:1 http://deb.debian.org/debian bullseye InRelease [113 kB]
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [36.8 kB]
Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [25.8 kB]
Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8178 kB]
Get:6 http://deb.debian.org/debian bullseye/non-free amd64 Packages [93.8 kB]
Fetched 8491 kB in 6s (1370 kB/s)
Reading package lists...
E: Unable to locate package crossbuild-essential
E: Unable to locate package libfdk-aac1:
The command '/bin/sh -c sed -Ei 's/main$/main non-free/g' /etc/apt/sources.list;         DEB_TARGET_ARCH="$(echo "$TARGETARCH$TARGETVARIANT" | sed -e "s/^armv6$/armel/" -e "s/^armv7$/armhf/" -e "s/^ppc64le$/ppc64el/" -e "s/^386$/i386/")";         dpkg --add-architecture "$DEB_TARGET_ARCH";         apt-get update;         apt-get install -qq --no-install-recommends             autoconf             libtool             crossbuild-essential-"$DEB_TARGET_ARCH"             libfdk-aac1:"$DEB_TARGET_ARCH"             libfdk-aac-dev:"$DEB_TARGET_ARCH"             portaudio19-dev:"$DEB_TARGET_ARCH"' returned a non-zero code: 100

```

**Comment by dubo-dubon-duponey** [comment]
> Same problem as @beagleboys

I do not think so. Their problem is that they run an old docker version.

> I direct set the platorm on docker file such as:
> 
> ```
> FROM    --platform=linux/amd64 golang:1.16   as fetcher
> ...
> ```

Do **not** do that.
You are just changing the *host* platform, not the *target* platform.


You are apparently on linux. For docker on linux, you apparently need:

```
docker buildx build --platform=linux/amd64 -t whatever .
```

And do NOT modify the Dockerfile (you should revert your changes).

@AlbanSeurat I will send another PR with more documentation about how to use Docker for people who are not used to it and/or a bullet-proof helper script that checks version.

**Comment by dubo-dubon-duponey** [comment]
Also, the maintainers of the golang official image changed it from buster to bullseye, effectively breaking our build.
PR also fix that.

@chenyg0911 use the dockerfile from [the last PR](https://github.com/openairplay/goplay2/pull/25), or manually replace `golang:1.16` with `golang:1.16-buster` in the Dockerfile.

**Comment by AlbanSeurat** [comment]
@dubo-dubon-duponey I have merged the PR.

let me know if this fix your issues

**Comment by dubo-dubon-duponey** [comment]
Thanks Alban

@chenyg0911 as stated above, you just have to:

docker buildx build -t you/goplay2 .

With the latest main branch and a recent enough docker (19.03 or more recent).

**Comment by beagleboys** [comment]
> @beagleboys From a cursory look, my guess is that your version of docker is ancient (are you using an old distro package?).
> Can we start by confirming that? (You can copy the output of 'docker info' here)

sorry for the delay(forgot I deactivated the email GitHub notifications).
I literally installed docker on a fresh copy of the rbp os using the instructions from the docker website... 
`pi@raspberrypi:~ $ docker -v
Docker version 20.10.8, build 3967b7d`

**Comment by dubo-dubon-duponey** [comment]
@beagleboys try the provided instructions above:

docker buildx build -t you/goplay2 .

**Comment by beagleboys** [comment]
> docker buildx build -t you/goplay2 .

pi@raspberrypi:~ $ sudo docker buildx build -t you/goplay2 .
[+] Building 0.3s (1/2)                                                                                                                                                                                 
 => [internal] load build definition from Dockerfile                                                                                                                                               0.2s
 => => transferring dockerfile: 2B                                                                                                                                                                 0.0s
error: failed to solve: failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount004100130/Dockerfile: no such file or directory


> @beagleboys try the provided instructions above:
> 
> docker buildx build -t you/goplay2 .

this is the output:

pi@raspberrypi:~ $ sudo docker buildx build -t you/goplay2 .
[+] Building 0.3s (1/2)                                                                                                                                                                                 
 => [internal] load build definition from Dockerfile                                                                                                                                               0.2s
 => => transferring dockerfile: 2B                                                                                                                                                                 0.0s
error: failed to solve: failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount004100130/Dockerfile: no such file or directory

**Comment by beagleboys** [comment]
> @beagleboys try the provided instructions above:
> 
> docker buildx build -t you/goplay2 .

it started, then ends like this:

`error: failed to solve: executor failed running [/bin/sh -c sed -Ei 's/main$/main non-free/g' /etc/apt/sources.list;         DEB_TARGET_ARCH="$(echo "$TARGETARCH$TARGETVARIANT" | sed -e "s/^armv6$/armel/" -e "s/^armv7$/armhf/" -e "s/^ppc64le$/ppc64el/" -e "s/^386$/i386/")";         dpkg --add-architecture "$DEB_TARGET_ARCH";         apt-get update;         apt-get install -qq --no-install-recommends             autoconf             libtool             crossbuild-essential-"$DEB_TARGET_ARCH"             libfdk-aac1:"$DEB_TARGET_ARCH"             libfdk-aac-dev:"$DEB_TARGET_ARCH"             portaudio19-dev:"$DEB_TARGET_ARCH"]: exit code: 100`

**Comment by dubo-dubon-duponey** [comment]
@beagleboys can you copy the relevant part of the logs please? This does not show the error.
Also did you update to the latest commit?

**Comment by dubo-dubon-duponey** [comment]
> @beagleboys
> Also did you update to the latest commit?

^ it does not seem like you did

Also, are you in China?

**Comment by beagleboys** [comment]
> @beagleboys can you copy the relevant part of the logs please? This does not show the error.

this is the output of the command with all the errors. where do I find the log?

> Also did you update to the latest commit?

I think I did. but I'll re download it to be sure.

**Comment by beagleboys** [comment]
> > @beagleboys can you copy the relevant part of the logs please? This does not show the error.
> 
> this is the output of the command with all the errors. where do I find the log?
> 
> > Also did you update to the latest commit?
> 
> I think I did. but I'll re download it to be sure.

ok, after I deleted and redownloaded the last commit it worked. it has issues with pulse audio but I got it working
