### ISSUE TITLE
Don't run.

### ISSUE THREAD

**Issue by xEzeit** [openairplay/goplay2#27]
Hello, this is my issue
pi@raspberrypi:/home/raye/goplay2 $ ./goplay2 -sink default:b1

2021/08/22 19:15:04 goplay/config.json is not valid - at new file will be created at program exit
2021/08/22 19:15:04 Starting goplay for device Pi: ca7e2ab8-ff55-49a2-b6ae-84385eb0323e, guid: ca7e2ab8-ff55-49a2-b6ae-84385eb0323e, Psi: ca7e2ab8-ff55-49a2-b6ae-84385eb0323e
2021/08/22 19:15:04 dial unix /run/user/1000/pulse/native: connect: connection refused
2021/08/22 19:15:04 Warning : impossible to store config file goplay/config.json
panic: dial unix /run/user/1000/pulse/native: connect: connection refused

goroutine 1 [running]:
log.Panic(0xd3feb0, 0x1, 0x1)
        /usr/local/go/src/log/log.go:354 +0x84
goplay2/codec.NewStream(0x2875b8, 0x64)
        /home/raye/goplay2/codec/pulseaudio.go:45 +0x80
goplay2/audio.NewPlayer(0xc9e438, 0xc94150, 0x147ae)
        /home/raye/goplay2/audio/player.go:32 +0x40
main.main()
        /home/raye/goplay2/main.go:71 +0x950

What it's wrong ? Thanks

**Comment by AlbanSeurat** [comment]
This seems to be the same problem as https://github.com/openairplay/goplay2/issues/16

Let met know if it does resolve or not your problem

**Comment by xEzeit** [comment]
Yes it's working, i have reinstall pulseaudio with https://github.com/shivasiddharth/PulseAudio-System-Wide and reboot and working. But i have a problem with delay in multiroom. It's not syncronize adding delay

> This seems to be the same problem as #16
> 
> Let met know if it does resolve or not your problem

Yes it's working, i have reinstall pulseaudio with https://github.com/shivasiddharth/PulseAudio-System-Wide and reboot and working. But i have a problem with delay in multiroom. It's not syncronize adding delay

**Comment by AlbanSeurat** [comment]
The multiroom part is working progress in the branch audio-sync
